### PR TITLE
Use minio console access as readiness check

### LINKED ISSUE #11: Minio is not ready even after `StartAndWaitReady` completes
## Issue description
Trying to start Minio on the latest version of `main`, the server is not ready to handle requests, despite `StartAndWaitReady` being ran successfully already. Any immediate requests afterwards result in error response `Server not initialized, please try again`.

I suspect this could be an issue with the readiness probe upstream, since when setting up the same scenario with code version from before Minio image update in https://github.com/efficientgo/e2e/pull/4, everything is working correctly. However, I haven't confirmed the exact cause yet.

## Minimal setup to reproduce
Run this test:
```
import (
	"context"
	"io/ioutil"
	"testing"

	"github.com/efficientgo/e2e"
        e2edb "github.com/efficientgo/e2e/db"
	"github.com/efficientgo/tools/core/pkg/testutil"
	"github.com/minio/minio-go/v7"
	"github.com/minio/minio-go/v7/pkg/credentials"
)

func TestMinio(t *testing.T) {
	e, err := e2e.NewDockerEnvironment("minio_test", e2e.WithVerbose())
	testutil.Ok(t, err)
	t.Cleanup(e.Close)

	const bucket = "minoiotest"
	m := e2edb.NewMinio(e, "minio", bucket)
	testutil.Ok(t, e2e.StartAndWaitReady(m))

	mc, err := minio.New(m.Endpoint("http"), &minio.Options{
		Creds: credentials.NewStaticV4(e2edb.MinioAccessKey, e2edb.MinioSecretKey, ""),
	})
	testutil.Ok(t, err)
	testutil.Ok(t, ioutil.WriteFile("test.txt", []byte("just a test"), 0755))

	_, err = mc.FPutObject(context.Background(), bucket, "obj", "./test.txt", minio.PutObjectOptions{})
	testutil.Ok(t, err)
}
```

### PR DESCRIPTION
**Pull request by douglascamata**
Signed-off-by: Douglas Camata <159076+douglascamata@users.noreply.github.com>

This should fix #11. As [my comment there](https://github.com/efficientgo/e2e/issues/11#issuecomment-1290903551) mentions, I applied the same solution used at https://github.com/thanos-io/thanos/pull/5615: using the MinIO console as readiness check. It has been working well there so far.

As an addition I added a small and basic test for the `NewMinio` function.

### CODE REVIEW

File: db/db.go [hunk 1]
```diff
@@ -109,11 +110,24 @@ func NewMinio(env e2e.Environment, name, bktName string, opts ...Option) *e2emon
...
+					f.Dir(),
+				),
+			),
+			Readiness: e2e.NewHTTPReadinessProbe(
+				consolePortName,
+				"/",
+				200,
+				200,
 			),
-			Readiness: e2e.NewHTTPReadinessProbe(AccessPortName, "/minio/health/live", 200, 200),
```
Comment (saswatamcode) [inline db/db.go:116]: This seems to be the liveness probe and not the readiness probe https://github.com/minio/minio/blob/master/docs/metrics/healthcheck/README.md#readiness-probe.

Maybe we can try switching to `minio/health/ready` and see if that works well? That way we can avoid having to load the full console. 🙂

File: db/db_test.go [hunk 2]
```diff
@@ -0,0 +1,22 @@
...
+
+func TestMinio(t *testing.T) {
+	t.Parallel()
+
+	e, err := e2e.New()
+	testutil.Ok(t, err)
+	t.Cleanup(e.Close)
+
+	minio := NewMinio(e, "mintest", "bkt")
+	testutil.Ok(t, e2e.StartAndWaitReady(minio))
```
Comment (saswatamcode) [inline db/db_test.go:21]: Maybe we should do some operation here, to validate that `StartAndWaitReady` returning actually means that minio is ready to receive requests?

**Review by saswatamcode — COMMENTED** [review]
Thanks! Some suggestions.

File: db/db.go (hunk 1 above)
Comment (douglascamata) [reply db/db.go:116]: We won't load the "full" console. As Javascript doesn't run, it's much more lightweight. It's also hacky, but it is what works 100% of the time.

Comment (douglascamata) [reply db/db.go:116]: In fact, MinIO's liveness and readiness check are exactly the same:

https://github.com/minio/minio/blob/444ff20bc5268d61b329c1d1bc7eb22aeb5f96de/cmd/healthcheck-handler.go#L98

Comment (saswatamcode) [reply db/db.go:116]: Oh wow! Ideally, this should be fixed on minio side. 
But since we already have working "console"-based one then I think this is fine then. 

Do you mind opening an issue on minio repo and linking here as a TODO, so that if this is ever fixed, we can update and remove hack here? 🙂

**Review by saswatamcode — APPROVED** [review]
LGTM minus test and TODO!

File: db/db.go (hunk 1 above)
Comment (douglascamata) [reply db/db.go:116]: I'll try to carve some time to create a snippet to reliably reproduce the issue and start a discussion over there. I prefer to not tie the creation of the issue there to merging work here, especially because their readiness probe "does what it says it does". It'll be more of a design question for them.

File: db/db_test.go (hunk 2 above)
Comment (douglascamata) [reply db/db_test.go]: Done at https://github.com/efficientgo/e2e/pull/58/commits/aa6fa59a54d16f3abeb03d45340d7dd569c02b15

**Comment by douglascamata** [comment]
The build is drunk. It complains that minio/minio-go/v7 isn't in the go.sum files, but it's there: https://github.com/efficientgo/e2e/pull/58/files#diff-3295df7234525439d778f1b282d146a4f1ff6b415248aaac074e8042d9f42d63R167

File: go.sum [hunk 3]
```diff
@@ -151,10 +162,18 @@ github.com/kr/text v0.1.0 h1:45sCR5RtlFHMR4UwH9sdQ5TC8v0qDQCHnXt+kaKSTVE=
 github.com/kr/text v0.1.0/go.mod h1:4Jbv+DJW3UT/LiOwJeYQe1efqtUx/iVham/4vfdArNI=
 github.com/matttproud/golang_protobuf_extensions v1.0.1 h1:4hp9jkHxhMHkqkrB3Ix0jegS5sx/RkqARlsWZ6pIwiU=
 github.com/matttproud/golang_protobuf_extensions v1.0.1/go.mod h1:D8He9yQNgCq6Z5Ld7szi9bcBfOoFv/3dc6xSMkL2PC0=
+github.com/minio/md5-simd v1.1.2 h1:Gdi1DZK69+ZVMoNHRXJyNcxrMA4dSxoYHZSQbirFg34=
+github.com/minio/md5-simd v1.1.2/go.mod h1:MzdKDxYpY2BT9XQFocsiZf/NKVtR7nkE4RoEpN+20RM=
+github.com/minio/minio-go/v7 v7.0.45 h1:g4IeM9M9pW/Lo8AGGNOjBZYlvmtlE1N5TQEYWXRWzIs=
+github.com/minio/minio-go/v7 v7.0.45/go.mod h1:nCrRzjoSUQh8hgKKtu3Y708OLvRLtuASMg2/nvmbarw=
```
Comment (douglascamata) [inline go.sum:168]: For some reason, the build tells me this doesn't exist.

File: db/db.go (hunk 1 above)
Comment (saswatamcode) [reply db/db.go:116]: Yeah, seems like they closed issue too. But IMO, readiness and liveness should mean diff things. Anyway, thanks for adding comment!
